### DISCUSSION TITLE
Liste von Icon-Sets und -Fonts

### DISCUSSION THREAD

**Discussion by deleonio** [public-ui/kolibri#681] [General]
> **Note**
> `Technisch können alle Icon-Fonts mit KoliBri verwendet werden.`

Folgende Icon-Sets und Icon-Fonts wurden schon mit KoliBri erprobt:

- https://fontawesome.com/
- https://icofont.com/
- https://microsoft.github.io/vscode-codicons/dist/codicon.html
- https://tablericons.com/

**Comment by deleonio** [comment]
Beispiel um Icons auszutauschen am Accordion:

```css
:host .open kol-icon::part(icon) {
  font-family: "Font Awesome 6 Free";
  font-weight: bold;
}
:host .open kol-icon::part(icon)::before {
  content: "\f077";
}

```
