### ISSUE TITLE
🛹 Feature: Toggle Button Konstruktion

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#3451]
Ursprung: https://github.com/public-ui/kolibri/issues/771
Stakeholder: @Chrisdo82 

Hi @deleonio, ich komme leider erst jetzt dazu die Styles für diese Komponente umzusetzen. Ich komme der Designvorlage mit dem Designer auch recht nah, allerdings schaffe ich es aufgrund der vorhandenen Struktur nicht die Styles für Hover & Focus richtig zu setzen. Auch dass das Inputfeld 44px hoch sein soll, aber optisch nur 32px hoch ist, lässt sich nicht gut umsetzen.

Im Prinzip bräuchte ich mindestens einen div-Wrapper ums label und input feld.

Anbei meine Styles, dann kannst du es im Designer selbst nachvollziehen.

```css
:host kol-input.button {
  cursor: inherit;
  display: grid;
  column-gap: 0;
  grid-template-columns: 32px auto;
  grid-template-areas:
    "error error"
    "input label"
    "hint hint";
}
:host kol-input.button > .error {
  grid-area: error;
}
:host kol-input.button > label {
  grid-area: label;
  background-color: var(--color-ice);
  border-top-right-radius: var(--border-radius);
  border-bottom-right-radius: var(--border-radius);
  min-height: 32px;
  align-items: center;
  display: flex;
  padding-right: 12px;
  width: 100%;
}
:host kol-input.button > .input {
  grid-area: input;
  background-color: var(--color-ice);
  border-top-left-radius: var(--border-radius);
  border-bottom-left-radius: var(--border-radius);
  min-height: 32px;
  min-width: 32px;
  place-content: center;
}
:host kol-input.button > .hint {
  grid-area: hint;
}
:host kol-input.button > .input > div {
  display: flex;
}
```
