### ISSUE TITLE
🛹 Feature: Tabs seitlich anordnen und nur Icons

### ISSUE THREAD

**Issue by AndreasZimnas** [public-ui/kolibri#378]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgegebe.

---

# Featureanfrage

## Bezieht sich Ihre Feature-Anfrage auf ein Problem? Bitte beschreiben.
Nein

## Beschreiben Sie die gewünschte Lösung
Wir würden es toll finden wenn die Tabs Komponente auch Vertikal platziert werden könnte. Für eine Vertikale Platzierung würden wir auch bevorzugen, die Option zu haben nur Icons, ohne Text, zu verwenden.

## Beschreiben Sie Alternativen, die Sie in Betracht gezogen haben
Keine

## Zusätzlicher Kontext
Beispiel von Vertikalen Tabs.
![vertikale-tabs](https://user-images.githubusercontent.com/28750796/199917765-6a0c7854-3a57-4f52-8ae2-6d3375d90544.png)

**Comment by deleonio** [comment]
@AndreasZimnas 

Forken Sie gerne das Repo und implementieren Sie eine seitliche Variant des Tabs. Wir schauen uns das an.

**Comment by deleonio** [comment]
@AndreasZimnas wir machen zu dem Thema einen gemeinsamen Workshop - und setzen das Feature gemeinsam um.

**Comment by deleonio** [comment]
@AndreasZimnas Die erweiterte Tabs Komponente steht bereit zum CSS-Styling: https://public-ui.github.io/designer/

![image](https://user-images.githubusercontent.com/6279703/203769284-39822bc0-a869-473c-bef4-898a79efe694.png)

```
_tabsAlign: 'top' | 'right' | 'bottom' | 'left'
```

**Comment by deleonio** [comment]
@cbraehmig / @ElVariablo 

Müssten wir die Tab-Reihenfolge ändern, auch wenn die Tabs rechts oder unter dem Tab-Inhalt angezeigt wird?

Simple wäre: es einfach so zu lassen - unabhängig von der Ausrichtung.

**Comment by deleonio** [comment]
Feedback:

- Hinweis, dass die Navigation ggf. weit vom Inhalt entfernt wäre.
- Tabreihenfolge?! - Muss in der Doku begründet werden.
- Option: Neues Property - Nav vor und nach Inhalt

**Comment by ElVariablo** [comment]
Sabine / Daniel:

Das Problem mit der Tabreihenfolge könnte gelöst werden, indem der Tab/Rgeister-Wechsel durch die Pfeiltasten geschieht. 
Das ist möglich, da es momentan keinen Festgelegten Standard für die Tastaturbedienung der Tabs gibt. 
Dadurch wäre eine effiziente Nutzung der einzelnen Tabs auch bei vielen bedienbaren Elementen innerhalb eines Tabs möglich, unabhängig von der Position der Positionierung der Tabs.

**Comment by deleonio** [comment]
@ElVariablo 
Der Tab-Wechsel erfolgt unabhängig der Ausrichtung mit den Pfeiltasten (<, >). Dazu muss aber der Fokus auf der Tab-Leiste sein.

Wenn die Tab-Leiste rechts oder gar unterhalb ist. Wäre man bei einer Vertauschung der Tab-Reihenfolge, immer erst durch den Inhalt tabben müssen.

Aktuell ist bei den Tabs immer die Tab-Leiste zu erst im Fokus und danach erst der Sprung in den Tab-Inhalt

**Comment by deleonio** [comment]
@AndreasZimnas Könnt Ihr bitte noch das Styling für das Release 1.1.13 liefern. Danke

**Comment by AndreasZimnas** [comment]
@deleonio Ich bin beim Styling auf ein Problem gestoßen. Ich kann die Tabs rechts, links oder unten platzieren, ich kann aber die Buttons dann nicht von oben nach unten platzieren, nur wenn die Tabs rechts oder links platziert sind. Ich kann also, wenn ich die Buttons platzieren möchte, nicht die Positionierung der Tabs herausfinden. Vielleicht könnt Ihr mir weiterhelfen. Hier was ich bis jetzt habe:

```
.tabs-align-right {
  display: grid;
  grid-template-columns: 1fr auto;
}

.tabs-align-right kol-button-group {
  order: 2;
}

:host(kol-button-group) div {
  display: grid;
  grid-template-columns: auto;
}

.tabs-align-right kol-button-group > div:first-child {
  margin: 0px 1em;
}
```

**Comment by deleonio** [comment]
Danke @AndreasZimnas - wir müssen die Komponente noch etwas flexibler machen. Hierzu werden wir statt der Shadow-Dom `button-group` die `button-group` ohne Shadow-Root verwenden.

![Image](https://user-images.githubusercontent.com/6279703/204456993-f7ed94c7-84a9-47c5-9c3d-d8fcec436c85.png)

Voraussichtlich mit RC.6 verfügbar.

```css
:host > .tabs-align-right {
  display: grid;
  grid-template-columns: 1fr auto;
}

:host > .tabs-align-right kol-button-group {
  display: grid;
  order: 2;
}

:host > .tabs-align-right > kol-button-group > div:first-child {
  margin: 0px 1em;
}
```

**Comment by deleonio** [comment]
# Version 1.1.13-rc.6 ist draußen

![Image](https://user-images.githubusercontent.com/6279703/204545950-974477a7-cf35-4cca-881f-4b080abd2d4f.png)


```css
:host {
  font-family: var(--font-family);
}
:host > div {
  display: block;
  width: 100%;
}
:host kol-button-group-wc {
  display: inline-block;
  border-radius: 0.25rem 0.25rem 0 0;
  background-color: var(--kolibri-color-normal);
}
:host kol-button-group-wc > div {
  display: inline-flex;
}
:host kol-button-group-wc > div + div {
  margin-left: 0.25em;
}
:host > div > div {
  padding: 0.25em;
  border: 1px solid var(--kolibri-border-color);
  border-radius: 0 0 0.25rem 0.25rem;
}
button {
  box-sizing: border-box;
  font-size: inherit;
  line-height: 1.25em;
  cursor: pointer;
  border-width: 2px;
  box-shadow: 0 0 0.25em gray;
  font-family: var(--kolibri-font-family);
  width: inherit;
  border-radius: var(--kolibri-border-radius);
  border-style: solid;
  padding: calc(2 * var(--kolibri-spacing));
  display: grid;
  gap: 0.25em;
  align-items: center;
  justify-content: center;
  text-align: center;
  transition-duration: 0.5s;
  transition-property: background-color, color, border-color;
}
kol-button-wc[aria-selected="true"] button {
  border-bottom-width: 0.25em !important;
  border-bottom-style: solid;
  border-bottom-color: var(--kolibri-color-accent) !important;
}
button > kol-span-wc span {
  display: flex;
  gap: 0.25em;
  align-items: center;
  justify-content: center;
}
button:disabled {
  cursor: not-allowed;
  opacity: 0.5;
}
button.primary,
button.primary:disabled:hover {
  background-color: var(--kolibri-color-primary);
  border-color: var(--kolibri-color-primary);
  color: white;
}
button.primary:hover,
button.primary:focus {
  color: var(--kolibri-color-primary);
}
button.secondary,
button.secondary:disabled:hover {
  background-color: var(--kolibri-color-secondary);
  border-color: var(--kolibri-color-secondary);
  color: white;
}
button.secondary:hover,
button.secondary:focus {
  color: var(--kolibri-color-secondary);
}
button.normal,
button.normal:disabled:hover {
  background-color: var(--kolibri-color-normal);
  border-color: var(--kolibri-color-normal);
  color: white;
}
button.normal:hover,
button.normal:focus {
  color: var(--kolibri-color-normal);
}
button.danger,
button.danger:disabled:hover {
  background-color: var(--kolibri-color-danger);
  border-color: var(--kolibri-color-danger);
  color: white;
}
button.danger:hover,
button.danger:focus {
  color: var(--kolibri-color-danger);
}
button.ghost,
button.ghost:disabled:hover {
  background-color: white;
  border-color: var(--kolibri-color-ghost);
  color: var(--kolibri-color-ghost);
}
button.ghost:hover,
button.ghost:focus {
  background-color: var(--kolibri-color-ghost);
  color: white;
}
button:hover,
button:focus {
  background-color: white;
  box-shadow: 0 0 0.25em black;
}
button:active {
  outline: 0 !important;
  box-shadow: none !important;
}
.close-button {
  font-size: 25%;
  height: fit-content;
  width: 0;
}
.close-button button {
  width: 1rem;
  position: relative;
  height: 1rem;
  left: -4.25em;
  top: 0.25em;
}

```
