### ISSUE TITLE
📖 Help: KolProgress - Breite nicht flexibel

### ISSUE THREAD

**Issue by Chrisdo82** [public-ui/kolibri#5239]
> **Note**
> - [x] Ich achte beim Erstellen des Issues darauf, dass ich **keine** fachlichen und unternehmensinternen Details preisgebe.

---

**Hilfeanfrage**

Wie kann im Designer die Breite der ProgressBar angepasst werden? Das SVG ist fix auf 100px gestellt. Das ist nicht ideal, da jede Veränderung mit CSS dafür sorgt, dass das SVG skaliert. Statt SVG wäre eine Lösung mit spans, divs und CSS wesentlich praktikabler. Was ist der Grund dafür, dass ihr hier SVGs verwendet habt?

```jsx
<div class="bar">
	{state._label && <div>{state._label}</div>}
	<div style={{ display: 'flex', gap: '0.3em' }}>
		<svg width="100" viewBox="0 0 102 8" xmlns="http://www.w3.org/2000/svg">
			<rect class="background" x="1" y="1" height="10" rx="5" fill="currentColor" stroke="currentColor" stroke-width="3" width="100"></rect>
			<rect
				class="progress"
				x="2.5"
				y="2.5"
				height="7"
				rx="3.5"
				fill="currentColor"
				stroke="currentColor"
				stroke-width="3"
				width={95 * (state._value / state._max)}
			></rect>
			<rect class="border" x="1" y="1" height="10" rx="5" fill="currentColor" stroke="currentColor" stroke-width="1" width="100"></rect>
		</svg>
		<text aria-hidden="true" text-anchor="middle" dominant-baseline="central" fill="currentColor">
			{state._value}
			{state._unit}
		</text>
	</div>
</div>
```

Das betrifft sowohl `.bar` als auch `.cycle`

**Comment by Chrisdo82** [comment]
Hiermit komme ich der Designvorlage am nächsten:

```css
.bar > div {
  flex-direction: column;
  gap: 0.5rem !important;
  width: 100px;
}
.bar > div text {
  color: var(--color-black);
  align-self: flex-end;
}
.bar svg {
  height: 1rem;
}
.bar .background {
  fill: var(--color-ice);
  stroke: var(--color-ice);
  stroke-width: 1px;
}
.bar .progress {
  fill: var(--color-midnight);
  stroke: var(--color-midnight);
}
.bar .border {
  display: none;
}

.cycle {
  overflow: visible;
}
.cycle .whitespace,
.cycle .border {
  stroke: transparent;
}
.cycle .background {
  stroke: var(--color-ice);
  stroke-width: 1rem;
}
.cycle .progress {
  stroke: var(--color-midnight);
  stroke-width: 1rem;
}
.cycle text:first-of-type {
  color: var(--color-grey);
  line-height: 1.25rem;
  alignment-baseline: after-edge;
}
.cycle text:last-of-type {
  color: var(--color-black);
  font-size: 1.75rem;
  font-weight: 700;
  line-height: 1.5rem;
  alignment-baseline: central;
}
```
