### ISSUE TITLE
🛹 Feature: Readonly by Input-Checkbox

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#5478]
Wir haben eine Anfrage, das Input um Readonly zu erweitern.

**Comment by deleonio** [comment]
Readonly ist am Input nicht funktional, nach W3C.

https://codesandbox.io/s/restless-fast-mn77t3?file=/src/index.html

**Comment by deleonio** [comment]
Der Readonly-State scheint nicht oder selten zu sein:

- https://ant.design/components/checkbox
- https://mui.com/material-ui/react-checkbox/
- https://m2.material.io/components/checkboxes#usage

**Comment by deleonio** [comment]
Wir haben darüber gesprochen, dass man die Sichtbarkeit und die Nicht-Änderbarkeit haben möchte.

Es gibt auch die Möglichkeit es nur als Text mit DT., DD darzustellen. Das ist jedoch nicht gewüschnt.

Kleiner Versuch als Wrapper-Component: https://codesandbox.io/s/kolibri-public-ui-react-static-form-sample-forked-sqvv95?file=/src/MyCheckbox.tsx

**Comment by deleonio** [comment]
Es ist möglich, eine Wrapper-Component zu schreiben, die das readonly-Property ergänzt.

Mittels einer CSS-Property könnte man den Style von `disabled` in einen neutralen Style ändern und den Wert mittels `disabled` sperren.

Alles ließe sich in einer eigenen Komponente kapseln.

Theme
```css
:host {
  --checkbox-readonly-opacity: 0.5;
}
.disabled {
  opacity: var(--checkbox-readonly-opacity);
}
```

App
```css
kol-input-checkbox.readonly {
  --checkbox-readonly-opacity: 1;
}
```

Verwendung
```html
<kol-input-checkbox class="readonly">
  <input disabled type="checkbox" />
</kol-input-checkbox>
```
