### ISSUE TITLE
🛠️ Todo: `border-width: 0 !important;` bei Alert-Styling prüfen

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#6169]
Wir haben beim Alert zuletzt überall `!important;` hinzugefügt. Wieso ist das notwendig? Können wir auch darauf verzichten?

- [x] Im Basisstyle darf kein Styling gemacht werden und auch kein `!important` gesetzt haben, damit man die Themes frei umsetzen kann.
- [x] Prüfen, ob es weitere `!important` gibt und hier im Ticket protokollieren.

**Comment by Makko74** [comment]
Im Basisstyle kann ich kein 

```css
border-width: 0 !important;
```
finden. Nur in den Themes, z.b Default Theme

**Comment by Makko74** [comment]
preset.scss

```css
 /*
 * Ensure elements with hidden attribute to be actually not visible
 * @see https://meowni.ca/hidden.is.a.lie.html
 */
[hidden] {
	display: none !important;
}
```

style.scss in src/components

```css
[aria-disabled='true']:focus .kol-span-wc,
[disabled]:focus .kol-span-wc {
	outline: none !important;
}
```

_kol-table-stateless-mixin.scss

```css
.focus-element:focus {
	outline: 0 !important;
}
```

style.scss in comobox

```css
&--disabled * {
	cursor: not-allowed !important;
}

&__item {
	cursor: pointer;

	.combobox__listbox--cursor-hidden & {
		cursor: none !important;
	}
}
```

style.scss in icon

```css
:host > i,
:host > i:before {
	font-size: inherit !important;
}
```

style.scss in input-radio

```css
@media (forced-colors: active) {
	input:checked:before {
		/* Give it a visible background in forced colors mode */
		background: selectedItem !important;
	}
}
```

style.scss in link-group

```css
li.list-none {
	list-style-type: none !important;
	margin-left: 0;
}
```

style.scss in single-select

```css
&.disabled * {
	cursor: not-allowed !important;
}

&__item {
	&.highlighted {
		background-color: #f0f0f0;
	}
	.single-select__listbox--cursor-hidden & {
		cursor: none !important;
	}
}
```
