### ISSUE TITLE
Rename `rem` method

### ISSUE THREAD

**Issue by deleonio** [public-ui/kolibri#7510]
Die `rem`-Methode ist schon belegt und wir sollten diese umbenennen.

Wir haben zudem 2 Implementierungen:

```scss
@function rem($size) {
	@return calc(#{$size}rem / var(--kolibri-root-font-size, 16));
}
```

```scss
@use 'sass:math';

$html-font-size: 16;
@function rem($pxValue) {
	@return #{math.div($pxValue, $html-font-size)}rem;
}
```
