### ISSUE TITLE
🛹 Feature: Toggle Button einführen

### ISSUE THREAD

**Issue by gretaneumannn** [public-ui/kolibri#771]
Funktion: Über die Toggle Badge soll das An- und Abwählen von Funktionen ermöglicht werden. Mit Klick ist es aktiviert und mit erneutem Klick wieder deaktiviert

<img width="562" alt="image" src="https://user-images.githubusercontent.com/118734593/203105818-68afa65a-1720-408e-b855-1762d6230625.png">

CSS-Styles: 
height: 32px;
width: 171px;
left: 26px;
top: 38px;
border-radius: 5px;
padding: 4px 12px 4px 8px;

**Comment by deleonio** [comment]
ToggleButton spezifisches Verhalten in einer neuen Komponente vom Typ Button verankern.

Es gibt eigene Props: toogleIcon, unToggleIcon, Ereignisse-CBs

Spricht dafür: einfacheres Styling, klares Verwendungsszenario

Erstmal 100 % API vom Button

**Comment by deleonio** [comment]
Hallo @Chrisdo82,

wir haben den Toggle-Button als weitere Variante der Checkbox umgesetzt. Im Grunde müssten wir einfach die neue Variante unter der CSS-Klasse `.button` stylen.

Spec: https://public-ui.github.io/docs/components/input-checkbox#properties

![image](https://user-images.githubusercontent.com/6279703/217199284-b9afb660-aaa7-4e50-8ef9-668f31b377bc.png)

Achtung: die neue Konstruktion hat den alten Style gebrochen, im ITZBund Theme ist das aber schon behoben.

**Comment by deleonio** [comment]
Komponente vorhanden - Styling muss auf Theme-Ebene vorgenommen werden.

**Comment by deleonio** [comment]
siehe auch https://github.com/public-ui/kolibri/issues/2652

**Comment by deleonio** [comment]
@gretaneumannn, @Chrisdo82 feature in 1.5-rc1 umgesetzt.

**Comment by Chrisdo82** [comment]
Hi @deleonio, ich komme leider erst jetzt dazu die Styles für diese Komponente umzusetzen. Ich komme der Designvorlage mit dem Designer auch recht nah, allerdings schaffe ich es aufgrund der vorhandenen Struktur nicht die Styles für Hover & Focus richtig zu setzen. Auch dass das Inputfeld 44px hoch sein soll, aber optisch nur 32px hoch ist, lässt sich nicht gut umsetzen.

Im Prinzip bräuchte ich mindestens einen div-Wrapper ums label und input feld.

Anbei meine Styles, dann kannst du es im Designer selbst nachvollziehen.

```css
:host kol-input.button {
  cursor: inherit;
  display: grid;
  column-gap: 0;
  grid-template-columns: 32px auto;
  grid-template-areas:
    "error error"
    "input label"
    "hint hint";
}
:host kol-input.button > .error {
  grid-area: error;
}
:host kol-input.button > label {
  grid-area: label;
  background-color: var(--color-ice);
  border-top-right-radius: var(--border-radius);
  border-bottom-right-radius: var(--border-radius);
  min-height: 32px;
  align-items: center;
  display: flex;
  padding-right: 12px;
  width: 100%;
}
:host kol-input.button > .input {
  grid-area: input;
  background-color: var(--color-ice);
  border-top-left-radius: var(--border-radius);
  border-bottom-left-radius: var(--border-radius);
  min-height: 32px;
  min-width: 32px;
  place-content: center;
}
:host kol-input.button > .hint {
  grid-area: hint;
}
:host kol-input.button > .input > div {
  display: flex;
}
```
