### ISSUE TITLE
`_variant` bei Headline entfernen

### ISSUE THREAD

**Issue by laske185** [public-ui/kolibri#7735]
`_variant` in V2 deprecaten
`_variant` in V3 entfernen

@deleonio:  In der Dokumentation V3 gibt es einen kleinen Abschnitt, wie das dennoch umgesetzt werden kann.

Erklärung:
Dass wir das Property entfernen, heißt nicht, dass es mit KoliBri nicht möglich wäre. Denn es ist möglich im Theme eine CSS-Property vorzuhalten, um die Gestaltung von Außern steuern zu können.

Auszug aus `kol-heading`-Styling:

```css
h1 {
  font-size: var(--prefix-heading-font-size, 2rem)
}
h2 {
  font-size: var(--prefix-heading-font-size, 1.75rem)
}
h3 {
  font-size: var(--prefix-heading-font-size, 1.5rem)
}
...
```

Auszug aus dem eigenen CSS-Styling:

```css
.as-h2 {
  --prefix-heading-font-size: 2rem;
}
```

Auszug bei der Verwendung von `kol-heading`:

```html
<kol-heading _label="Hello world!" _level="3" class="as-h2"></kol-heading>
```
